- block:
  - name: "[component] {{ name|upper }} debug"
    debug:
      msg: "{{ componentObj| to_nice_json }}"
      verbosity: 1
  - name: "{{ name|upper }} render Dir"
    include_tasks: render_dir.yml
    tags: always
  - name: "[component] {{ name|upper }} files"
    include_tasks: files.yml
    vars:
      filesObj: "{{ componentObj.files | default({}) }}"
    tags: files
  - name: "[component] {{ name|upper }} install"
    include_tasks: install.yml
    vars:
      installObj: "{{ componentObj.install | default({}) }}"
    tags: install
  - name: "[component] {{ name|upper }} configs"
    include: configs.yml
    vars:
      configsObj: "{{ componentObj.configs | default({}) }}"
    tags: configs
  - name: "[component] {{ name|upper }} runConfigs"
    include: run_configs.yml
    vars:
      runConfigsObj: "{{ componentObj.run_configs | default({}) }}"
    tags: run_configs
  - name: "[component] {{ name|upper }} run"
    include: run.yml
    vars:
      runObj: "{{ componentObj.run | default({}) }}"
    tags: run
  - name: "[component] {{ name|upper }} plugins"
    include_tasks:
      file: plugin.yml
    with_items: '{{ current_plugins }}'
    loop_control:
      loop_var: current_plugin
    vars:
      name: 'plugin {{ current_plugin }}'
      pluginObj: '{{ componentObj.plugins[current_plugin] }}'
    tags: plugins
  tags: role_component

