---
# FILES
- block:
  - name: "[file] {{ name|upper }} local debug"
    debug:
      msg: "{{ filesObj | to_nice_json }}"
      verbosity: 2
  - name: "[file] {{ name|upper }} local facts"
    set_fact:
      files:      "{{ filesObj.file | default([]) }}"
      files_pre:  "{{ filesObj.pre  | default([]) }}"
      files_post: "{{ filesObj.post | default([]) }}"
  - include_tasks: cmd.yml
    vars:
      prefix: files
      type: pre
      content: "{{ files_pre }}"
    when: files_pre
  - name: "[file] {{ name|upper }} copy files"
    copy:
      src:   "{{ file.src  }}"
      dest:  "{{ file.dest }}"
      owner: "{{ file.owner  | default(role_component.user)  }}"
      group: "{{ file.group  | default(role_component.group) }}"
      mode:  "{{ file.mode   | default(role_component.mode)  }}"
    no_log:  "{{ file.secret | default(false) }}"
    with_items: "{{ files }}"
    loop_control:
      loop_var: file
  - include_tasks: cmd.yml
    vars:
      prefix: files
      type: post
      content: "{{ files_post }}"
    when: files_post
  tags:
  - plugin
  - files
