---
# TEMPLATE
- block:
  - name: "[template] {{ template|upper }} local facts"
    set_fact:
      template_src:   "{{ templates[template].template | default('') }}"
      template_dest:  "{{ templates[template].config | default('') }}"
      template_owner: "{{ templates[template].owner | default(role_component.user)  }}"
      template_group: "{{ templates[template].group | default(role_component.group) }}"
      template_mode:  "{{ templates[template].mode  | default(role_component.mode)  }}"
      template_type:  "{{ templates[template].type  | default('jinja')  }}"
      template_no_log: "{{templates[template].no_log| default(false)                }}"
      template_backup: "{{templates[template].backup| default(role_component.backup)}}"
      template_become: "{{templates[template].become| default(false)}}"
  - name: "[template] {{ template|upper }} template folder"
    file:
      path:  "{{ template_dest | dirname }}"
      state: directory
    # when: template_src
  - name: "[template] {{ template|upper }} template - {{ template_dest }} {{ template_owner }}:{{ template_group }} {{ template_mode }}"
    no_log:  "{{ template_no_log}}"
    template:
      src:   "{{ template_src   }}"
      dest:  "{{ template_dest  }}"
      owner: "{{ template_owner }}"
      group: "{{ template_group }}"
      mode:  "{{ template_mode  }}"
      backup: "{{ template_backup }}"
    become: "{{ template_become }}"
    # when: template_src
